// Today = 2026-04-26

export type Lead = {
  id: string;
  name: string;
  phone: string;
  altPhone?: string;
  source: "call" | "society" | "walkin" | "whatsapp" | "referral" | "other";
  societyId?: string;
  campaignId?: string;
  vehicleInfo?: { make: string; model: string; year?: number; registration?: string };
  issueDescription?: string;
  preliminaryDiagnosis?: string;
  preferredServiceType?: "doorstep" | "garage" | "either";
  schedulingPreference?: "specific" | "range" | "anytime";
  preferredDate?: string;
  preferredDateRange?: { from: string; to: string };
  status: "new" | "contacted" | "qualified" | "booked" | "lost" | "on_hold";
  lostReason?: string;
  tags: string[];
  assignedOpsId: string;
  followUpDate?: string;
  notes: { id: string; text: string; createdAt: string; createdBy: string }[];
  activity: { id: string; type: string; description: string; timestamp: string }[];
  createdAt: string;
  neighbourhood?: string;
};

export const leads: Lead[] = [
  // New leads (last 48h) — for dashboard "New Leads" tab
  {
    id: "l1",
    name: "Arun Gowda",
    phone: "9880123456",
    source: "whatsapp",
    vehicleInfo: { make: "Hyundai", model: "Venue", year: 2022 },
    issueDescription: "Car shaking at high speeds. Wheel balancing needed?",
    preferredServiceType: "doorstep",
    schedulingPreference: "specific",
    preferredDate: "2026-04-28",
    status: "new",
    tags: [],
    assignedOpsId: "u3",
    notes: [],
    activity: [{ id: "a1", type: "lead_created", description: "Lead created via WhatsApp", timestamp: "2026-04-26T07:30:00" }],
    neighbourhood: "JP Nagar",
    createdAt: "2026-04-26T07:30:00",
  },
  {
    id: "l2",
    name: "Bhavana Reddy",
    phone: "9741234500",
    source: "society",
    societyId: "soc1",
    campaignId: "camp2",
    vehicleInfo: { make: "Maruti", model: "Dzire", year: 2021, registration: "KA01ZZ5555" },
    issueDescription: "PUC expired, need renewal + general check.",
    preferredServiceType: "doorstep",
    schedulingPreference: "range",
    preferredDateRange: { from: "2026-04-29", to: "2026-05-03" },
    status: "new",
    tags: ["Flexible"],
    assignedOpsId: "u4",
    notes: [],
    activity: [{ id: "a2", type: "lead_created", description: "Captured at Prestige Lakeside activation", timestamp: "2026-04-25T14:00:00" }],
    neighbourhood: "Whitefield",
    createdAt: "2026-04-25T14:00:00",
  },
  {
    id: "l3",
    name: "Chetan Kulkarni",
    phone: "9632890000",
    source: "call",
    vehicleInfo: { make: "Honda", model: "Amaze", year: 2020 },
    issueDescription: "AC not working. Car parked for 2 weeks.",
    preferredServiceType: "garage",
    schedulingPreference: "specific",
    preferredDate: "2026-04-27",
    status: "new",
    tags: [],
    assignedOpsId: "u3",
    notes: [],
    activity: [{ id: "a3", type: "lead_created", description: "Inbound call captured by Rohan", timestamp: "2026-04-25T11:00:00" }],
    neighbourhood: "Indiranagar",
    createdAt: "2026-04-25T11:00:00",
  },
  {
    id: "l4",
    name: "Divya Shetty",
    phone: "8971560000",
    source: "referral",
    vehicleInfo: { make: "Tata", model: "Harrier", year: 2023 },
    issueDescription: "Strange noise from suspension on bumps.",
    preferredServiceType: "either",
    schedulingPreference: "anytime",
    status: "new",
    tags: ["Flexible"],
    assignedOpsId: "u4",
    notes: [],
    activity: [{ id: "a4", type: "lead_created", description: "Referred by Rajesh Kumar (c1)", timestamp: "2026-04-25T09:00:00" }],
    neighbourhood: "Marathahalli",
    createdAt: "2026-04-25T09:00:00",
  },
  {
    id: "l5",
    name: "Eshan Verma",
    phone: "9900345000",
    source: "whatsapp",
    vehicleInfo: { make: "Kia", model: "Sonet", year: 2022 },
    issueDescription: "Annual service. Looking for good price.",
    preferredServiceType: "doorstep",
    schedulingPreference: "range",
    preferredDateRange: { from: "2026-04-28", to: "2026-05-05" },
    status: "new",
    tags: ["Price-sensitive"],
    assignedOpsId: "u3",
    notes: [],
    activity: [{ id: "a5", type: "lead_created", description: "WhatsApp inquiry", timestamp: "2026-04-25T08:00:00" }],
    neighbourhood: "Indiranagar",
    createdAt: "2026-04-25T08:00:00",
  },
  // Contacted leads
  {
    id: "l6",
    name: "Farzana Begum",
    phone: "8123400000",
    source: "society",
    societyId: "soc2",
    vehicleInfo: { make: "Honda", model: "City", year: 2019 },
    issueDescription: "Brake pads + oil change needed.",
    preferredServiceType: "doorstep",
    schedulingPreference: "specific",
    preferredDate: "2026-04-30",
    status: "contacted",
    tags: [],
    assignedOpsId: "u4",
    followUpDate: "2026-04-27T11:00:00",
    notes: [{ id: "n1", text: "Spoke to her. Available Saturday morning. Will confirm.", createdAt: "2026-04-24T14:00:00", createdBy: "Priya Sharma" }],
    activity: [
      { id: "a6", type: "lead_created", description: "Captured at Sobha Dream Acres activation", timestamp: "2026-04-22T15:00:00" },
      { id: "a7", type: "call", description: "Called — spoke for 4 mins. Interested.", timestamp: "2026-04-24T13:58:00" },
    ],
    neighbourhood: "Marathahalli",
    createdAt: "2026-04-22T15:00:00",
  },
  {
    id: "l7",
    name: "Ganesh Prasad",
    phone: "9845560000",
    source: "call",
    vehicleInfo: { make: "Maruti", model: "Swift Dzire", year: 2018 },
    issueDescription: "Engine warning light on.",
    preferredServiceType: "garage",
    schedulingPreference: "specific",
    preferredDate: "2026-04-29",
    status: "contacted",
    tags: [],
    assignedOpsId: "u3",
    followUpDate: "2026-04-26T14:00:00",
    notes: [{ id: "n2", text: "Sent WhatsApp with pricing. Waiting for reply.", createdAt: "2026-04-25T10:00:00", createdBy: "Rohan Mehta" }],
    activity: [
      { id: "a8", type: "lead_created", description: "Inbound call", timestamp: "2026-04-23T16:00:00" },
      { id: "a9", type: "whatsapp", description: "WhatsApp sent with pricing sheet", timestamp: "2026-04-25T09:55:00" },
    ],
    neighbourhood: "Koramangala",
    createdAt: "2026-04-23T16:00:00",
  },
  // Qualified leads
  {
    id: "l8",
    name: "Harini Rao",
    phone: "9741670000",
    source: "referral",
    vehicleInfo: { make: "Toyota", model: "Camry", year: 2020 },
    issueDescription: "Full service + AC check.",
    preferredServiceType: "doorstep",
    schedulingPreference: "specific",
    preferredDate: "2026-05-03",
    status: "qualified",
    tags: ["Premium"],
    assignedOpsId: "u4",
    followUpDate: "2026-04-28T10:00:00",
    notes: [
      { id: "n3", text: "High-value customer. Wants premium service. Quote sent ₹8500.", createdAt: "2026-04-24T11:00:00", createdBy: "Priya Sharma" },
    ],
    activity: [
      { id: "a10", type: "lead_created", description: "Referred by Arvind Bhat (c5)", timestamp: "2026-04-23T09:00:00" },
      { id: "a11", type: "call", description: "Qualification call — 12 mins", timestamp: "2026-04-24T10:48:00" },
    ],
    neighbourhood: "JP Nagar",
    createdAt: "2026-04-23T09:00:00",
  },
  {
    id: "l9",
    name: "Iqbal Sheikh",
    phone: "9980780000",
    source: "whatsapp",
    vehicleInfo: { make: "Mercedes", model: "E-Class", year: 2021 },
    issueDescription: "Sunroof leaking + AC smells musty.",
    preferredServiceType: "garage",
    schedulingPreference: "range",
    preferredDateRange: { from: "2026-04-29", to: "2026-05-06" },
    status: "qualified",
    tags: ["Premium", "VIP"],
    assignedOpsId: "u3",
    followUpDate: "2026-04-27T15:00:00",
    notes: [{ id: "n4", text: "High-end car. Will require senior mechanic. Quote ₹12000 sent.", createdAt: "2026-04-25T16:00:00", createdBy: "Rohan Mehta" }],
    activity: [
      { id: "a12", type: "lead_created", description: "WhatsApp inquiry", timestamp: "2026-04-24T20:00:00" },
      { id: "a13", type: "call", description: "Discovery call — 8 mins", timestamp: "2026-04-25T15:50:00" },
    ],
    neighbourhood: "Indiranagar",
    createdAt: "2026-04-24T20:00:00",
  },
  // On hold
  {
    id: "l10",
    name: "Jayalakshmi Iyer",
    phone: "8765890000",
    source: "call",
    vehicleInfo: { make: "Hyundai", model: "Tucson", year: 2022 },
    issueDescription: "Suspension work — got quote from another garage, comparing.",
    preferredServiceType: "garage",
    schedulingPreference: "specific",
    preferredDate: "2026-05-10",
    status: "on_hold",
    tags: ["Price-sensitive"],
    assignedOpsId: "u4",
    followUpDate: "2026-05-01T10:00:00",
    notes: [{ id: "n5", text: "Price-shopping. Follow up on May 1st to see if she's decided.", createdAt: "2026-04-20T14:00:00", createdBy: "Priya Sharma" }],
    activity: [
      { id: "a14", type: "lead_created", description: "Inbound call", timestamp: "2026-04-19T11:00:00" },
      { id: "a15", type: "call", description: "Called — price objection. Comparing quotes.", timestamp: "2026-04-20T13:55:00" },
    ],
    neighbourhood: "HSR Layout",
    createdAt: "2026-04-19T11:00:00",
  },
  // Booked
  {
    id: "l11",
    name: "Kiran Srivastava",
    phone: "9632900000",
    source: "society",
    societyId: "soc3",
    vehicleInfo: { make: "Renault", model: "Kwid", year: 2020 },
    issueDescription: "AC service + general check.",
    preferredServiceType: "doorstep",
    schedulingPreference: "specific",
    preferredDate: "2026-04-27",
    status: "booked",
    tags: [],
    assignedOpsId: "u3",
    notes: [],
    activity: [
      { id: "a16", type: "lead_created", description: "Captured at Brigade Meadows activation", timestamp: "2026-04-20T14:00:00" },
      { id: "a17", type: "status_change", description: "Status changed to Booked — SR created", timestamp: "2026-04-25T10:00:00" },
    ],
    neighbourhood: "Kanakapura Road",
    createdAt: "2026-04-20T14:00:00",
  },
  // Lost
  {
    id: "l12",
    name: "Lavanya Murthy",
    phone: "9741010000",
    source: "call",
    vehicleInfo: { make: "Toyota", model: "Glanza", year: 2021 },
    issueDescription: "Oil change.",
    preferredServiceType: "either",
    schedulingPreference: "specific",
    preferredDate: "2026-04-15",
    status: "lost",
    lostReason: "Went to authorised service center",
    tags: [],
    assignedOpsId: "u4",
    notes: [{ id: "n6", text: "Toyota ASC offered free service under warranty. Can't compete.", createdAt: "2026-04-15T15:00:00", createdBy: "Priya Sharma" }],
    activity: [
      { id: "a18", type: "lead_created", description: "Inbound call", timestamp: "2026-04-12T10:00:00" },
      { id: "a19", type: "status_change", description: "Marked lost — warranty service at ASC", timestamp: "2026-04-15T14:55:00" },
    ],
    neighbourhood: "Koramangala",
    createdAt: "2026-04-12T10:00:00",
  },
  // More leads for variety
  {
    id: "l13",
    name: "Manoj Nair",
    phone: "8971120000",
    source: "walkin",
    vehicleInfo: { make: "Mahindra", model: "XUV700", year: 2023 },
    issueDescription: "Brake service + tyre pressure check.",
    preferredServiceType: "garage",
    schedulingPreference: "anytime",
    status: "new",
    tags: ["Flexible"],
    assignedOpsId: "u3",
    notes: [],
    activity: [{ id: "a20", type: "lead_created", description: "Walk-in at garage", timestamp: "2026-04-24T12:00:00" }],
    neighbourhood: "Marathahalli",
    createdAt: "2026-04-24T12:00:00",
  },
  {
    id: "l14",
    name: "Nalini Sharma",
    phone: "9845230000",
    source: "society",
    societyId: "soc4",
    vehicleInfo: { make: "Maruti", model: "Ertiga", year: 2022 },
    issueDescription: "Vibration at 80 kmph — wheel balancing.",
    preferredServiceType: "doorstep",
    schedulingPreference: "specific",
    preferredDate: "2026-04-28",
    status: "contacted",
    tags: [],
    assignedOpsId: "u4",
    followUpDate: "2026-04-27T09:00:00",
    notes: [],
    activity: [
      { id: "a21", type: "lead_created", description: "Captured at Mantri Tranquil activation", timestamp: "2026-04-23T11:00:00" },
      { id: "a22", type: "call", description: "Called — confirmed. Sending mechanic Apr 28.", timestamp: "2026-04-24T09:00:00" },
    ],
    neighbourhood: "Subramanyapura",
    createdAt: "2026-04-23T11:00:00",
  },
  {
    id: "l15",
    name: "Om Prakash",
    phone: "9900450000",
    source: "referral",
    vehicleInfo: { make: "Jeep", model: "Compass", year: 2021 },
    issueDescription: "4WD service + engine oil.",
    preferredServiceType: "garage",
    schedulingPreference: "range",
    preferredDateRange: { from: "2026-05-01", to: "2026-05-08" },
    status: "qualified",
    tags: ["Premium"],
    assignedOpsId: "u3",
    followUpDate: "2026-04-30T15:00:00",
    notes: [{ id: "n7", text: "Referred by Suresh Rao. Quote ₹9500 sent.", createdAt: "2026-04-25T12:00:00", createdBy: "Rohan Mehta" }],
    activity: [
      { id: "a23", type: "lead_created", description: "Referred by Suresh Rao (c3)", timestamp: "2026-04-24T16:00:00" },
      { id: "a24", type: "call", description: "Qualification call — 6 mins", timestamp: "2026-04-25T11:55:00" },
    ],
    neighbourhood: "JP Nagar",
    createdAt: "2026-04-24T16:00:00",
  },
  // More scattered leads for the list page
  { id: "l16", name: "Padmini Krishnan", phone: "9741340000", source: "call", vehicleInfo: { make: "Toyota", model: "Urban Cruiser", year: 2022 }, issueDescription: "General service.", preferredServiceType: "doorstep", schedulingPreference: "anytime", status: "on_hold", tags: ["Flexible"], assignedOpsId: "u4", notes: [], activity: [], createdAt: "2026-04-18T09:00:00", neighbourhood: "Koramangala" },
  { id: "l17", name: "Qasim Ali", phone: "8765450000", source: "whatsapp", vehicleInfo: { make: "Honda", model: "Jazz", year: 2019 }, issueDescription: "Engine rattling noise.", preferredServiceType: "garage", schedulingPreference: "specific", preferredDate: "2026-05-02", status: "new", tags: [], assignedOpsId: "u3", notes: [], activity: [{ id: "a25", type: "lead_created", description: "WhatsApp", timestamp: "2026-04-26T10:00:00" }], createdAt: "2026-04-26T10:00:00", neighbourhood: "Marathahalli" },
  { id: "l18", name: "Rekha Patel", phone: "9980560000", source: "society", societyId: "soc5", vehicleInfo: { make: "Tata", model: "Punch", year: 2022 }, issueDescription: "Dent repair + polish.", preferredServiceType: "garage", schedulingPreference: "range", preferredDateRange: { from: "2026-05-05", to: "2026-05-12" }, status: "contacted", tags: [], assignedOpsId: "u4", notes: [], activity: [], createdAt: "2026-04-22T14:00:00", neighbourhood: "Marathahalli" },
  { id: "l19", name: "Suresh Pillai", phone: "9632670000", source: "referral", vehicleInfo: { make: "BMW", model: "X5", year: 2022 }, issueDescription: "Scheduled maintenance.", preferredServiceType: "garage", schedulingPreference: "specific", preferredDate: "2026-05-05", status: "qualified", tags: ["VIP", "Premium"], assignedOpsId: "u3", followUpDate: "2026-04-29T14:00:00", notes: [], activity: [], createdAt: "2026-04-21T10:00:00", neighbourhood: "Indiranagar" },
  { id: "l20", name: "Tanya Mehta", phone: "9741780000", source: "walkin", vehicleInfo: { make: "Hyundai", model: "Verna", year: 2021 }, issueDescription: "AC gas refill.", preferredServiceType: "doorstep", schedulingPreference: "specific", preferredDate: "2026-04-29", status: "booked", tags: [], assignedOpsId: "u4", notes: [], activity: [], createdAt: "2026-04-20T11:00:00", neighbourhood: "HSR Layout" },
  { id: "l21", name: "Uday Bhat", phone: "8971890000", source: "call", vehicleInfo: { make: "Skoda", model: "Kushaq", year: 2022 }, issueDescription: "Service overdue.", preferredServiceType: "garage", schedulingPreference: "anytime", status: "lost", lostReason: "No response after 3 follow-ups", tags: [], assignedOpsId: "u3", notes: [], activity: [], createdAt: "2026-04-10T09:00:00", neighbourhood: "Koramangala" },
  { id: "l22", name: "Vani Gopalakrishnan", phone: "9845900000", source: "society", societyId: "soc1", vehicleInfo: { make: "Maruti", model: "Baleno", year: 2023 }, issueDescription: "First service check.", preferredServiceType: "doorstep", schedulingPreference: "range", preferredDateRange: { from: "2026-04-30", to: "2026-05-07" }, status: "new", tags: ["Flexible"], assignedOpsId: "u4", notes: [], activity: [{ id: "a26", type: "lead_created", description: "Society activation", timestamp: "2026-04-25T16:00:00" }], createdAt: "2026-04-25T16:00:00", neighbourhood: "Whitefield" },
  { id: "l23", name: "Wasim Khan", phone: "9900010000", source: "whatsapp", vehicleInfo: { make: "MG", model: "Hector", year: 2022 }, issueDescription: "Check engine light.", preferredServiceType: "garage", schedulingPreference: "specific", preferredDate: "2026-04-28", status: "contacted", tags: [], assignedOpsId: "u3", notes: [], activity: [], createdAt: "2026-04-23T17:00:00", neighbourhood: "JP Nagar" },
  { id: "l24", name: "Xavier Fernandes", phone: "9741120000", source: "referral", vehicleInfo: { make: "Volkswagen", model: "Tiguan", year: 2021 }, issueDescription: "Wheel alignment + tyres.", preferredServiceType: "garage", schedulingPreference: "range", preferredDateRange: { from: "2026-05-03", to: "2026-05-10" }, status: "qualified", tags: ["Premium"], assignedOpsId: "u4", followUpDate: "2026-04-30T10:00:00", notes: [], activity: [], createdAt: "2026-04-22T10:00:00", neighbourhood: "Indiranagar" },
  { id: "l25", name: "Yamuna Devi", phone: "8765230000", source: "call", vehicleInfo: { make: "Honda", model: "Activa 125", year: 2021 }, issueDescription: "2-wheeler service.", preferredServiceType: "doorstep", schedulingPreference: "anytime", status: "new", tags: ["Flexible", "Price-sensitive"], assignedOpsId: "u3", notes: [], activity: [{ id: "a27", type: "lead_created", description: "Inbound call", timestamp: "2026-04-26T08:00:00" }], createdAt: "2026-04-26T08:00:00", neighbourhood: "HSR Layout" },
];
